travis:
  secure:
    BINSTAR_TOKEN: BUY0vla+QChP3KVhBk/saL3FvMZKS2b40yJsq0Ns4LZ+eAQyUWwmqKFe/EhtHG7eRZFBA3SXcIdKP3MuADa08HKOirQqLDXe8KzOt8fisSO3YArVQGJfvQjKHFlS4NCMuhkVnY1C1NCZ6o8zIt6DQhP6VV1DAvCG/2zlGc8FOS5J/bX7f2tOqJmOO49qOWI57EQiau29XRwH31wDYs49U+w/KJtNxgPyuT0rSJgOBUss8SEwP8nRtBLryXYbfQWp2y3pM6nIZxWEh9Ym1HvQuZf7Bdu/BBcxk6+KCKenEH7u+IUPy3sHX1GN/hY+MeyBdeC3btHTfFLW0+6wy6pbuKg0BMQfxTnndv2yrviVtmakIOF4szzvU7+LqDL74cD8qW2em8/BsI8BHCIOv1lYBCvF/xu6rIYAuay7DPCd8O3wl5F8sh7xxYufsArcrNMsn6vnu+HJ4l6RJ6vqqowb9gzjUYSVZzgsHaTHmeVAJH6XncLyRlMXVRq+KsTXvDBrxPsgFaW3kGtY/Q0H8lInkhGFyR1FdACvPUkEps/vjjE5fPplcXae70BboqG4icdLiWI9yAw4d2pHYBoMbOzc8o+QX/Ig718L0YESl8uNiMvLROTGDpLeMdjzY9rreu+c24l1b6kquo42OUUDaQNQkxAzgLf/MmI40dFwDk5y+Gg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
