travis:
  secure:
    BINSTAR_TOKEN: 0CK0e7fre/n9HnjjSV2+s/UdC2G4z2OMYzfY7SB6G5wlPp0dltaf15LxZM2bfv3g8uL+scQzJ/trxBn23YYBe5SSf1BLoAHK3WlWJC6INYIdfdzMOPRKamKl0W8v66B9yihOxGVVIFcvHgPCKomRR977UrFhQA6LzXN2B2Ku70R6wxR6+9NeW7jKvwDHHnhE4DIcVYEzYhh/odF3AhOhVyW9b5uICIHzjy+Pubkq2M9akHfvCG2dbm3lXRSE7LtHiOny1G4hHNUhwfbCAv4wi5YxdNyzq/tuLIWcb8nNqlLHoiByLSHv92z6YP58MyqSqHEdDeFoHgu1JXLz8sDt1OS5HBU82J7UoATjesMZN0PB9iWrjLT8olHWj2ax3VZ+FS2vhpq7oc+tlZxB8vuOadxGz3G6eV8zMA3xOJ/nEQ+meDsmhWFIRNwF7Y/xHwdnaZuxPssOXJ6eGjlKppn9Xil+URZjyVgZ/jsp1j4mzA/+/2m/xjccRSZfiil+kOCkjD5SVQQu1xnvh4yFFbZdWiz6oDlcFQy5q3Jj/GtSxpbxDdWdVHDel/6DnyuXpBCDmm3RipLS/w5ERcVnZpY1PKoPdBWvpa8eJQVVwzc45hy3mbOj9F8Q439aDgPmRNWeqhwAtrYYIp6rf4UGPX6Tf8CZYklurz+pKyiQqlNmYGk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
