travis:
  secure:
    BINSTAR_TOKEN: O27K8F4CNFG4Hi4L2OxfRT0x6wq8zHezNamu6oHsZyTIg+FdRmSG5wAmrmlge+GlWKsF1p3tMLkpEZ5YPcZjrZqgyK82cChVBcyYQNeB4vfCDBFQ6aro7pQAoeCL7TpbziFLIiaEuJWdOeYLBXYGiWqCn3EFc3U5ydSeirX8pMc7uR5XolFbaAueSptUcLN2DOw6+KsoWNhj9VuZR6IYJv9WKTPJdDXfYCZrMmol4CGKNYpJ0bdm+AX+TJJVm2pbZ0GB26xgBhT3RAF1SZoYuFBhwypZRMz13yJSXuBaz+UFK3d1BRxBTb7bAu1AtU6KI+w6z9YpDHj5E2+VSffF+9i5VsQYdr3TyQtsl8oxinii/icaBLiK4mB2xsSF1V6F6piK1du9+3L2BZw6ppyg7k3DZhSMFDsDgj87cdF5JCNTfxWACQLa91CoMq32W8k4HRq0juhWPLFPYfIUvyer1a4uBqpGOhgYRXVg34c69yqM7KM9ATVkg4km0hQoVnh1HySa78jA4W34PJOJoc2YfbCpiGROQgvq+PTnuZEM+0DaWYHAJkYO1qttsApPtC476si6lrf0rDDe39mypKQA0BuI/7N29j/B3JDqQu3UIjJz25JBZIPSl5KCz6CZiNEuDtvANHmyPkOvLXTkbt9Op9k2NyTauI18IZUoUE3Lffc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
